name: calendar
services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: calendar
            POSTGRES_PASSWORD: calendar
            POSTGRES_DB: calendar

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U calendar -d alendar"]
            interval: 2s
            timeout: 5s
            retries: 10

        ports:
            - "35432:5432"