scanInterval = 60

[logger]
level = "INFO"

[storage]
type = "sql"
dsn = "postgres://calendar:calendar@localhost:35432/calendar?sslmode=disable"

[amqp]
uri = "amqp://guest:guest@localhost:35672/"
exchange = "calendar"
exchangeType = "direct"
routingKey = "notifications"
queue = "sender"